package br.ufpe.cin.tool.db.entities;

// Generated Oct 31, 2013 7:37:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * AssociatedContext generated by hbm2java
 */
public class AssociatedContext implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int programId;
	private Program program;
	private String userTwitter;
	private Set<Hashtags> hashtagses = new HashSet<Hashtags>(0);

	public AssociatedContext() {
	}

	public AssociatedContext(Program program) {
		this.program = program;
	}

	public AssociatedContext(Program program, String userTwitter,
			Set<Hashtags> hashtagses) {
		this.program = program;
		this.userTwitter = userTwitter;
		this.hashtagses = hashtagses;
	}

	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	public String getUserTwitter() {
		return this.userTwitter;
	}

	public void setUserTwitter(String userTwitter) {
		this.userTwitter = userTwitter;
	}

	public Set<Hashtags> getHashtagses() {
		return this.hashtagses;
	}

	public void setHashtagses(Set<Hashtags> hashtagses) {
		this.hashtagses = hashtagses;
	}

}
