package br.ufpe.cin.tool.db.entities;

// Generated Oct 29, 2013 11:09:49 AM by Hibernate Tools 4.0.0

/**
 * Epg generated by hbm2java
 */
public class Epg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String country;
	private String datestart;
	private String timestart;
	private String duration;
	private String channelName;
	private String programName;
	private String descriptor;

	public Epg() {
	}

	public Epg(int id) {
		this.id = id;
	}

	public Epg(int id, String country, String datestart, String timestart,
			String duration, String channelName, String programName,
			String descriptor) {
		this.id = id;
		this.country = country;
		this.datestart = datestart;
		this.timestart = timestart;
		this.duration = duration;
		this.channelName = channelName;
		this.programName = programName;
		this.descriptor = descriptor;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getDatestart() {
		return this.datestart;
	}

	public void setDatestart(String datestart) {
		this.datestart = datestart;
	}

	public String getTimestart() {
		return this.timestart;
	}

	public void setTimestart(String timestart) {
		this.timestart = timestart;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	public String getDescriptor() {
		return this.descriptor;
	}

	public void setDescriptor(String descriptor) {
		this.descriptor = descriptor;
	}

}
