package br.ufpe.cin.tool.db.entities;


// Generated Oct 30, 2013 5:03:56 PM by Hibernate Tools 4.0.0

/**
 * EpgEvent generated by hbm2java
 */
public class EpgEvent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id = 0;
	private Program program;
	private String descriptor;
	private String startdate;
	private String starttime;
	private String durationtime;

	public EpgEvent() {
	}

	public EpgEvent(Program program) {
//		this.id = id;
		this.program = program;
	}

	public EpgEvent(Program program, String descriptor,
			String startdate, String starttime, String durationtime) {
//		this.id = id;
		this.program = program;
		this.descriptor = descriptor;
		this.startdate = startdate;
		this.starttime = starttime;
		this.durationtime = durationtime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	public String getDescriptor() {
		return this.descriptor;
	}

	public void setDescriptor(String descriptor) {
		this.descriptor = descriptor;
	}

	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getDurationtime() {
		return this.durationtime;
	}

	public void setDurationtime(String durationtime) {
		this.durationtime = durationtime;
	}

}
