package br.ufpe.cin.tool.db.entities;


// Generated Oct 31, 2013 4:33:08 PM by Hibernate Tools 4.0.0

/**
 * Hashtags generated by hbm2java
 */
public class Hashtags implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private AssociatedContext associatedContext;
	private String value;

	public Hashtags() {
	}

	public Hashtags(int id, AssociatedContext associatedContext) {
		this.id = id;
		this.associatedContext = associatedContext;
	}

	public Hashtags(int id, AssociatedContext associatedContext,
			String value) {
		this.id = id;
		this.associatedContext = associatedContext;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public AssociatedContext getAssociatedContext() {
		return this.associatedContext;
	}

	public void setAssociatedContext(
			AssociatedContext associatedContext) {
		this.associatedContext = associatedContext;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
