package br.ufpe.cin.tool.db.entities;

// Generated Oct 31, 2013 7:37:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int programId;
	private Broadcaster broadcaster;
	private String name;
	private Set<EpgEvent> epgEvents = new HashSet<EpgEvent>(0);
	private AssociatedContext associatedContext;

	public Program() {
	}

	public Program(int programId, Broadcaster broadcaster, String name) {
		this.programId = programId;
		this.name = name;
		this.broadcaster = broadcaster;
	}

	public Program(int programId, Broadcaster broadcaster, String name,
			Set<EpgEvent> epgEvents, AssociatedContext associatedContext) {
		this.programId = programId;
		this.broadcaster = broadcaster;
		this.name = name;
		this.epgEvents = epgEvents;
		this.associatedContext = associatedContext;
	}

	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	public Broadcaster getBroadcaster() {
		return this.broadcaster;
	}

	public void setBroadcaster(Broadcaster broadcaster) {
		this.broadcaster = broadcaster;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<EpgEvent> getEpgEvents() {
		return this.epgEvents;
	}

	public void setEpgEvents(Set<EpgEvent> epgEvents) {
		this.epgEvents = epgEvents;
	}

	public AssociatedContext getAssociatedContext() {
		return this.associatedContext;
	}

	public void setAssociatedContext(AssociatedContext associatedContext) {
		this.associatedContext = associatedContext;
	}

}
