package br.ufpe.cin.tool.db.entities;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.hibernate.annotations.GenericGenerator;

// Generated Oct 29, 2013 11:09:49 AM by Hibernate Tools 4.0.0

/**
 * Terms generated by hbm2java
 */
public class Terms implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GenericGenerator(name="gen",strategy="increment")
	@GeneratedValue(generator="gen")
	private int id;
	private String word;
	private Integer status;

	public Terms() {
	}

	public Terms(int id) {
		this.id = id;
	}

	public Terms(int id, String word, Integer status) {
		this.id = id;
		this.word = word;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
