package br.ufpe.cin.tool.db.entities;

// Generated Oct 29, 2013 11:09:49 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Tweets generated by hbm2java
 */
public class Tweets implements java.io.Serializable {

	private int id;
	private Date datecreation;
	private String geolocation;
	private String keyWord;
	private String post;

	public Tweets() {
	}

	public Tweets(int id) {
		this.id = id;
	}

	public Tweets(int id, Date datecreation, String geolocation,
			String keyWord, String post) {
		this.id = id;
		this.datecreation = datecreation;
		this.geolocation = geolocation;
		this.keyWord = keyWord;
		this.post = post;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public String getGeolocation() {
		return this.geolocation;
	}

	public void setGeolocation(String geolocation) {
		this.geolocation = geolocation;
	}

	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

}
