package br.ufpe.cin.tool.db.dao;

// Generated Oct 29, 2013 11:09:49 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Broadcaster generated by hbm2java
 */
public class Broadcaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id = 0;
	private String name;
	private Integer channel;
	private String country;
	private String language;
	private Set<Program> programs = new HashSet<Program>(0);

	public Broadcaster() {
	}

//	public Broadcaster(int id) {
//		this.id = id;
//	}

	public Broadcaster(String name, Integer channel, String country,
			String language, Set<Program> programs) {
//		this.id = id;
		this.name = name;
		this.channel = channel;
		this.country = country;
		this.language = language;
		this.programs = programs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getChannel() {
		return this.channel;
	}

	public void setChannel(Integer channel) {
		this.channel = channel;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public Set<Program> getPrograms() {
		return this.programs;
	}

	public void setPrograms(Set<Program> programs) {
		this.programs = programs;
	}

}
