package br.ufpe.cin.tool.db.dao;

// Generated Oct 29, 2013 11:09:49 AM by Hibernate Tools 4.0.0

/**
 * Program generated by hbm2java
 */
public class Program implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Broadcaster broadcaster;
	private String name;

	public Program() {
	}

	public Program(int id, Broadcaster broadcaster) {
		this.id = id;
		this.broadcaster = broadcaster;
	}

	public Program(int id, Broadcaster broadcaster, String name) {
		this.id = id;
		this.broadcaster = broadcaster;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Broadcaster getBroadcaster() {
		return this.broadcaster;
	}

	public void setBroadcaster(Broadcaster broadcaster) {
		this.broadcaster = broadcaster;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
