package br.ufpe.cin.tool.db.dao;

// Generated Oct 30, 2013 5:03:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id = 0;
	private Broadcaster broadcaster;
	private String name;
	private Set<EpgEvent> epgEvents = new HashSet<EpgEvent>(0);

	public Program() {
	}

	public Program(Broadcaster broadcaster, String name) {
//		this.id = id;
		this.broadcaster = broadcaster;
		this.name = name;
	}

	public Program(Broadcaster broadcaster, String name,
			Set<EpgEvent> epgEvents) {
//		this.id = id;
		this.broadcaster = broadcaster;
		this.name = name;
		this.epgEvents = epgEvents;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Broadcaster getBroadcaster() {
		return this.broadcaster;
	}

	public void setBroadcaster(Broadcaster broadcaster) {
		this.broadcaster = broadcaster;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<EpgEvent> getEpgEvents() {
		return this.epgEvents;
	}

	public void setEpgEvents(Set<EpgEvent> epgEvents) {
		this.epgEvents = epgEvents;
	}

}
